/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JiraDateTimeField {
    #[serde(rename = "dateTime")]
    pub date_time: Box<models::JiraDateTimeInput>,
    #[serde(rename = "fieldId")]
    pub field_id: String,
}

impl JiraDateTimeField {
    pub fn new(date_time: models::JiraDateTimeInput, field_id: String) -> JiraDateTimeField {
        JiraDateTimeField {
            date_time: Box::new(date_time),
            field_id,
        }
    }
}

