/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiTeam {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "teamType")]
    pub team_type: TeamType,
}

impl PublicApiTeam {
    pub fn new(description: String, display_name: String, organization_id: String, team_id: String, team_type: TeamType) -> PublicApiTeam {
        PublicApiTeam {
            description,
            display_name,
            organization_id,
            team_id,
            team_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TeamType {
    #[serde(rename = "OPEN")]
    Open,
    #[serde(rename = "MEMBER_INVITE")]
    MemberInvite,
    #[serde(rename = "EXTERNAL")]
    External,
}

impl Default for TeamType {
    fn default() -> TeamType {
        Self::Open
    }
}

