/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiMembershipFetchPayload {
    /// Pagination cursor, only members after the cursor will be returned
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// Maximum number of members to be returned
    #[serde(rename = "first", skip_serializing_if = "Option::is_none")]
    pub first: Option<i32>,
}

impl PublicApiMembershipFetchPayload {
    pub fn new() -> PublicApiMembershipFetchPayload {
        PublicApiMembershipFetchPayload {
            after: None,
            first: None,
        }
    }
}

