/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiMembershipAddResponse {
    #[serde(rename = "errors")]
    pub errors: Vec<models::PublicApiMembershipAddResponseErrorsInner>,
    #[serde(rename = "members")]
    pub members: Vec<models::PublicApiMembership>,
}

impl PublicApiMembershipAddResponse {
    pub fn new(errors: Vec<models::PublicApiMembershipAddResponseErrorsInner>, members: Vec<models::PublicApiMembership>) -> PublicApiMembershipAddResponse {
        PublicApiMembershipAddResponse {
            errors,
            members,
        }
    }
}

