/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiPageInfoAccountId {
    #[serde(rename = "endCursor", skip_serializing_if = "Option::is_none")]
    pub end_cursor: Option<String>,
    #[serde(rename = "hasNextPage")]
    pub has_next_page: bool,
}

impl PublicApiPageInfoAccountId {
    pub fn new(has_next_page: bool) -> PublicApiPageInfoAccountId {
        PublicApiPageInfoAccountId {
            end_cursor: None,
            has_next_page,
        }
    }
}

