/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiMembershipRemovePayload {
    #[serde(rename = "members")]
    pub members: Vec<models::PublicApiMembership>,
}

impl PublicApiMembershipRemovePayload {
    pub fn new(members: Vec<models::PublicApiMembership>) -> PublicApiMembershipRemovePayload {
        PublicApiMembershipRemovePayload {
            members,
        }
    }
}

