/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiUserPermissions {
    #[serde(rename = "ADD_MEMBERS")]
    pub add_members: bool,
    #[serde(rename = "DELETE_TEAM")]
    pub delete_team: bool,
    #[serde(rename = "REMOVE_MEMBERS")]
    pub remove_members: bool,
    #[serde(rename = "UPDATE_TEAM")]
    pub update_team: bool,
}

impl PublicApiUserPermissions {
    pub fn new(add_members: bool, delete_team: bool, remove_members: bool, update_team: bool) -> PublicApiUserPermissions {
        PublicApiUserPermissions {
            add_members,
            delete_team,
            remove_members,
            update_team,
        }
    }
}

