/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiTeamResponseWithMembers {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "members")]
    pub members: Vec<models::PublicApiMembership>,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "teamType")]
    pub team_type: TeamType,
    #[serde(rename = "userPermissions")]
    pub user_permissions: Box<models::PublicApiUserPermissions>,
}

impl PublicApiTeamResponseWithMembers {
    pub fn new(description: String, display_name: String, members: Vec<models::PublicApiMembership>, organization_id: String, team_id: String, team_type: TeamType, user_permissions: models::PublicApiUserPermissions) -> PublicApiTeamResponseWithMembers {
        PublicApiTeamResponseWithMembers {
            description,
            display_name,
            members,
            organization_id,
            team_id,
            team_type,
            user_permissions: Box::new(user_permissions),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TeamType {
    #[serde(rename = "OPEN")]
    Open,
    #[serde(rename = "MEMBER_INVITE")]
    MemberInvite,
    #[serde(rename = "EXTERNAL")]
    External,
}

impl Default for TeamType {
    fn default() -> TeamType {
        Self::Open
    }
}

