/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiMembershipRemoveResponse {
    #[serde(rename = "errors")]
    pub errors: Vec<models::PublicApiMembershipAddResponseErrorsInner>,
}

impl PublicApiMembershipRemoveResponse {
    pub fn new(errors: Vec<models::PublicApiMembershipAddResponseErrorsInner>) -> PublicApiMembershipRemoveResponse {
        PublicApiMembershipRemoveResponse {
            errors,
        }
    }
}

