/*
 * Teams Public API
 *
 * Teams Public API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiFetchResponsePublicApiMembershipAccountId {
    #[serde(rename = "pageInfo")]
    pub page_info: Box<models::PublicApiPageInfoAccountId>,
    #[serde(rename = "results")]
    pub results: Vec<models::PublicApiMembership>,
}

impl PublicApiFetchResponsePublicApiMembershipAccountId {
    pub fn new(page_info: models::PublicApiPageInfoAccountId, results: Vec<models::PublicApiMembership>) -> PublicApiFetchResponsePublicApiMembershipAccountId {
        PublicApiFetchResponsePublicApiMembershipAccountId {
            page_info: Box::new(page_info),
            results,
        }
    }
}

